
language: ruby

rvm:
  - 2.2.3

env:
  - NEO4J_VERSION=community-2.2.3

notifications:
  email: false

before_script:

  # Enable PostGIS.
  - psql -U postgres -c "CREATE EXTENSION POSTGIS"

  # Create database, apply Travis config.
  - psql -c "CREATE DATABASE travis_ci_test;" -U postgres
  - cp config/database.yml.travis config/database.yml

  # Install Neo4j.
  - bundle exec rake neo4j:install[$NEO4J_VERSION,test]
  - bundle exec rake neo4j:config[test,7474]
  - bundle exec rake neo4j:start[test]

  # Install Solr.
  - bundle exec rake sunspot:solr:start

  # Load the schema.
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
